### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sagreus** [cta-sst-1m/digicampipe#98] opened 2018-01-25 11:35 UTC
I got this error message when running "read_raw_events.py" or "pipeline_crab.py" with the display activated.
It appears when calling "display.draw()". Full error message is:

```
Traceback (most recent call last):
  File "read_raw_events.py", line 39, in <module>
    display.draw()
  File "/home/paco/CTA/ctasoft/src/digicamviewer/digicamviewer/viewer.py", line 160, in draw
    self.next()
  File "/home/paco/CTA/ctasoft/src/digicamviewer/digicamviewer/viewer.py", line 150, in next
    self.update()
  File "/home/paco/CTA/ctasoft/src/digicamviewer/digicamviewer/viewer.py", line 154, in update
    self.draw_readout(self.pixel_id)
  File "/home/paco/CTA/ctasoft/src/digicamviewer/digicamviewer/viewer.py", line 178, in draw_readout
    y = self.compute_trace()[pixel]
TypeError: 'type' object is not subscriptable
```

**Comment by dneise** [comment] 2018-01-25 12:26
Thanks for reporting :-D

Could you show me what exactly you typed in?

**Comment by sagreus** [comment] 2018-01-25 12:31
For instance:
python read_raw_events.py -d ./digicampipe/tests/resources/ -f example_100_evts.%03d.fits.fz -c ./../src/cts/config/camera_config.cfg

Should reproduce the problem.

**Comment by dneise** [comment] 2018-01-25 12:33
Yes it does reproduce, thanks ... looking into it.

**Comment by dneise** [comment] 2018-01-25 12:53
I have never worked with the viewer yet, but @calispac actually opened an issue regarding this problem.

#56 

I have opened a PR to fix this hopefully.

https://github.com/cta-sst-1m/digicamviewer/pull/4

**Comment by calispac** [comment] 2018-01-25 13:52
Somehow the DataContainer is empty. Probably because the viewer is looking at the wrong telescope.

**Comment by dneise** [comment] 2018-02-12 11:56
@sagreus This issue should be fixed since 18 days or so. 
Does it work for you?

**Comment by sagreus** [comment] 2018-02-12 13:14
@dneise Sorry for not answering back, I was a bit busy the last couple of weeks. The problem is solved, although I found another issue:
  File "./pipeline_crab.py", line 158, in <module>
    main(args)
  File "./pipeline_crab.py", line 147, in main
    display.draw()
  File "/home/paco/CTA/ctasoft2/src/digicamviewer/digicamviewer/viewer.py", line 160, in draw
    self.next()
  File "/home/paco/CTA/ctasoft2/src/digicamviewer/digicamviewer/viewer.py", line 121, in next
    telescope_id = event.r0.tels_with_data[0]
AttributeError: 'NoneType' object has no attribute 'r0'

For instance, when running:
./pipeline_crab.py   --baseline_path=./dark.npz   --outfile_path=./hillas_output.txt ./digicampipe/tests/resources/example_100_evts.000.fits.fz --display

It seems unrelated so maybe it is better to close this "issue" and open different one?

**Comment by dneise** [comment] 2018-02-12 13:42
Yes it would be good to open a fresh issue :-D

**Comment by yrenier** [comment] 2018-02-13 15:36
Closing the issue as it seems to be solved

**Closed by yrenier** 2018-02-13 15:36 UTC
