### ISSUE TITLE
Installation digicampipe

### ISSUE THREAD

**Issue by vasylbeshley** [cta-sst-1m/digicampipe#212] opened 2018-06-13 09:25 UTC
Hi all!

I have installed digicampipe on my laptop. Unfortunately, digicam-view don't work for me. I have error.

```
(digicampipe) vasyl@debv:~$ digicam-view /home/vasyl/CTA/digicampipe/SST1M_01_0_000.006.fits.fz 
WARNING:matplotlib.legend:No handles with labels found to put in legend.
Events:   0%|                                                                                                              | 0/12701 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/bin/digicam-view", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-view')()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/scripts/digicamview.py", line 15, in entry
    display.draw()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/visualization/__init__.py", line 205, in draw
    self.next()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/visualization/__init__.py", line 148, in next
    for i, event in zip(range(step), self.event_stream):
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/io/event_stream.py", line 50, in event_stream
    for event in data_stream:
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/io/zfits.py", line 90, in zfits_event_source
    desc='Events', leave=False):
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 30, in __next__
    return Event(event, self.run_id)
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 62, in __init__
    self.baseline = self.unsorted_baseline[Event._sort_ids]
IndexError: index 332 is out of bounds for axis 1 with size 0
```

Does somebody know what the problem is?

**Comment by dneise** [comment] 2018-06-13 09:35
Hello Vasyl, thanks for reporting this problem, to me this looks like a bug.

The bug seems to be triggered by the fact that the file you are trying to view does not contain a "digicam_baseline" field and the viewer seems to be not robust enough to handle this case. This is most likely a bug and not a problem on your side. 

If you like, you could try to view one of the test-files which are delivered together with digicampipe, just to make sure the viewer can view *some files* and there is no general problem hidden somewhere.

If I remember correctly the intended behavior of the viewer is: If there is no baseline, then it is simply not used, but the viewer still works.

Just to check: I assume you are working on the most recent version of digicampipe?

**Comment by dneise** [comment] 2018-06-13 09:58
I opened a pull request in order to hopefully fix this issue, maybe you could try that out and tell us if it works.

**Comment by vasylbeshley** [comment] 2018-06-13 10:51
Hello Dominik!
Thanks for your response. You are right, this is a problem with my ....fits.fz file. Test files are working. 
Ok, I'll test new protozfits reader version.

**Comment by dneise** [comment] 2018-06-14 08:44
Fixed in PR #213 (digicampipe v1.5)

**Closed by dneise** 2018-06-14 08:44 UTC

**Comment by dneise** [comment] 2018-06-14 09:38
Hey @vasylbeshley ... another question: I must admit, I do not know who you are :-D could you tell me what you are working on?

**Comment by vasylbeshley** [comment] 2018-06-14 10:04
Hi! 
Sorry, I forgot to introduce myself:). I am working with polish team of SST1M (Rafal Moderski, Dorota Sobczynska).  I will try to implement muon ring reconstruction to digicampipe.

**Comment by dneise** [comment] 2018-06-14 10:04
Very nice ... thank you very much
